apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-config-learning-apps
spec:
  source:
    directory:
      recurse: true
    repoURL: https://github.com/mchhikara85/applications-config
    targetRevision: main
    path: non-production/learning-apps
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true